"""empty message

Revision ID: 63d03419accb
Revises: fb6fc2be01bd
Create Date: 2023-11-10 19:38:23.002024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d03419accb'
down_revision = 'fb6fc2be01bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema='content') as batch_op:
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_unique_constraint('profile_email_uniq', ['email', 'email_verified'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema='content') as batch_op:
        batch_op.drop_constraint('profile_email_uniq', type_='unique')
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
