"""empty message

Revision ID: ba0798d14d79
Revises: 63d03419accb
Create Date: 2023-11-25 09:33:09.418649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba0798d14d79'
down_revision = '63d03419accb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema='content') as batch_op:
        batch_op.add_column(sa.Column('telegram', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema='content') as batch_op:
        batch_op.drop_column('instagram')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('telegram')
    # ### end Alembic commands ###
