"""empty message

Revision ID: fb6fc2be01bd
Revises: 1b09f7263881
Create Date: 2023-11-10 19:20:37.940979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb6fc2be01bd'
down_revision = '1b09f7263881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history_2023_10', schema='content')
    with op.batch_alter_table('permissions', schema='content') as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('profiles', schema='content') as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))

    with op.batch_alter_table('roles', schema='content') as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('users', schema='content') as batch_op:
        batch_op.create_unique_constraint(None, ['public_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='content') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('roles', schema='content') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('profiles', schema='content') as batch_op:
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email')

    with op.batch_alter_table('permissions', schema='content') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('login_history_2023_10',
    sa.Column('public_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['public_address'], ['content.users.public_address'], name='login_history_public_address_fkey'),
    sa.PrimaryKeyConstraint('public_address', 'datetime', name='login_history_2023_10_pkey'),
    schema='content'
    )
    # ### end Alembic commands ###
