# Generated by Django 4.1 on 2023-02-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft_tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="status",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("mint_1", "Mint 1"),
                    ("mint_2", "Mint 2"),
                    ("stop", "Stop"),
                    ("sold_out", "Sold Out"),
                ],
                default="stop",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="pack",
            name="status",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("mint_1", "Mint 1"),
                    ("mint_2", "Mint 2"),
                    ("stop", "Stop"),
                    ("sold_out", "Sold Out"),
                ],
                default="stop",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="status",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("mint_1", "Mint 1"),
                    ("mint_2", "Mint 2"),
                    ("stop", "Stop"),
                    ("sold_out", "Sold Out"),
                ],
                default="stop",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
