# Generated by Django 4.1.7 on 2023-05-01 16:42
import random

import django.core.validators
from django.db import migrations, models


def random_number(length):
    letters = "1234567890"
    rand_string = "".join(random.choice(letters) for i in range(length))
    return rand_string


def generate_symbol(apps, schema_editor):
    Collection = apps.get_model("nft_tokens", "Collection")
    for company in Collection.objects.all().iterator():
        symbol = "CBC" + random_number(3)
        while Collection.objects.filter(symbol=symbol).exists():
            symbol = "CBC" + random_number(3)

        company.symbol = symbol
        company.save()


class Migration(migrations.Migration):
    dependencies = [
        ("nft_tokens", "0002_collection_status_alter_pack_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="symbol",
            field=models.CharField(max_length=6, null=True, verbose_name="symbol"),
            preserve_default=False,
        ),
        migrations.RunPython(
            generate_symbol,
        ),
        migrations.AlterField(
            model_name="collection",
            name="symbol",
            field=models.SlugField(max_length=6, unique=True, verbose_name="symbol"),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name="collection",
            name="url",
            field=models.SlugField(unique=True, verbose_name="url"),
        ),
        migrations.AlterField(
            model_name="page",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pages/",
                validators=[
                    django.core.validators.FileExtensionValidator(["svg", "png"])
                ],
                verbose_name="icon",
            ),
        ),
    ]
