# Generated by Django 4.1.7 on 2023-05-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft_tokens", "0003_collection_symbol_alter_collection_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="application_form",
        ),
        migrations.AddField(
            model_name="collection",
            name="application_form",
            field=models.CharField(
                default="basic", max_length=255, verbose_name="application form"
            ),
        ),
    ]
