# Generated by Django 4.1.7 on 2023-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "nft_tokens",
            "0005_alter_token_unique_together_collection_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="number",
        ),
        migrations.AlterField(
            model_name="token",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="number"
            ),
        ),
    ]
