# Generated by Django 4.1.7 on 2023-05-02 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "nft_tokens",
            "0006_alter_token_unique_together_remove_collection_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="category_opensea",
        ),
    ]
