# Generated by Django 4.1.7 on 2023-10-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft_tokens", "0007_remove_collection_category_opensea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="symbol",
            field=models.SlugField(
                max_length=7, unique=True, verbose_name="symbol"
            ),
        ),
    ]
