# Generated by Django 4.1.7 on 2023-12-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft_tokens", "0009_token_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Email владельца",
            ),
        ),
        migrations.AlterField(
            model_name="pack",
            name="wallet_owner",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="wallet_owner",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="wallet_owner",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="wallet_owner",
            ),
        ),
    ]
