# Generated by Django 4.1.7 on 2024-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft_tokens", "0012_alter_pack_price_alter_token_price"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pack",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hide", False)),
                fields=("collection", "name"),
                name="pack_uniq_name_and_collection",
            ),
        ),
        migrations.AddConstraint(
            model_name="token",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hide", False)),
                fields=("collection", "name"),
                name="token_uniq_name_and_collection",
            ),
        ),
        migrations.AddConstraint(
            model_name="token",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hide", False)),
                fields=("collection", "number"),
                name="token_uniq_number_and_collection",
            ),
        ),
    ]
