# Generated by Django 4.1.7 on 2024-03-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft_tokens", "0013_pack_pack_uniq_name_and_collection_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pack",
            name="pack_uniq_name_and_collection",
        ),
        migrations.RemoveConstraint(
            model_name="token",
            name="token_uniq_name_and_collection",
        ),
        migrations.RemoveConstraint(
            model_name="token",
            name="token_uniq_number_and_collection",
        ),
        migrations.AddConstraint(
            model_name="pack",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hide", False)),
                fields=("collection", "name"),
                name="pack_uniq_name_and_collection",
                violation_error_message=(
                    "Пакет с таким именем в выбранной коллекции уже"
                    " существует."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="token",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hide", False)),
                fields=("collection", "name"),
                name="token_uniq_name_and_collection",
                violation_error_message=(
                    "Сертификат с таким именем в выбранной коллекции уже"
                    " существует."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="token",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hide", False)),
                fields=("collection", "number"),
                name="token_uniq_number_and_collection",
                violation_error_message=(
                    "Сертификат с таким номером в выбранной коллекции уже"
                    " существует."
                ),
            ),
        ),
    ]
