# Generated by Django 4.1.7 on 2023-11-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "social_opportunities",
            "0002_alter_company_options_alter_contacts_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("unique", "Unique"),
                    ("premium", "Premium"),
                    ("vip", "VIP"),
                ],
                default="unique",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="status_moderator",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("correct", "Correct"),
                    ("approved", "Approved"),
                    ("blocked", "Blocked"),
                ],
                default="correct",
                max_length=15,
            ),
        ),
    ]
