# Generated by Django 4.1.7 on 2023-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_opportunities", "0003_service_certificate_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="status_moderator",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("correct", "Correct"),
                    ("approved", "Approved"),
                    ("blocked", "Blocked"),
                ],
                default="correct",
                max_length=15,
            ),
        ),
    ]
