# Generated by Django 4.1.7 on 2023-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_opportunities", "0004_alter_service_status_moderator"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="manager_telegram",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="manager_whatsapp",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
