# Generated by Django 4.1.7 on 2023-11-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_opportunities", "0006_usedservice"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usedservice",
            constraint=models.UniqueConstraint(
                fields=("service", "token"), name="service_token_uniq"
            ),
        ),
    ]
