# Generated by Django 4.1.7 on 2023-12-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_opportunities", "0009_cooperation"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="manager_email",
            field=models.EmailField(
                default="info@checkbrand.com",
                max_length=254,
                verbose_name="manager_email",
            ),
            preserve_default=False,
        ),
    ]
