# Generated by Django 4.1.7 on 2023-12-23 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("nft_tokens", "0012_alter_pack_price_alter_token_price"),
        ("social_opportunities", "0010_service_manager_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Почта"),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("view", "Просмотрено"), ("new", "Новое")],
                        default="new",
                        max_length=15,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application",
                        to="social_opportunities.service",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nft_tokens.token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на использование сервиса",
                "verbose_name_plural": "Заявки на использование сервиса",
                "db_table": 'social_opportunities"."application',
            },
        ),
    ]
