"""create inital tables

Revision ID: 09a991741020
Revises: 
Create Date: 2022-09-24 21:05:01.593834

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09a991741020'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('white', 'reserve', 'delete', 'waiting', name='statusapplicationenum'), nullable=True),
    sa.Column('collection_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('token_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_wallet', sa.String(), nullable=True),
    sa.Column('moderator_wallet', sa.String(), nullable=True),
    sa.Column('discord_name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('in_work', sa.Boolean(), nullable=True),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application', schema='content')
    # ### end Alembic commands ###
