"""updated

Revision ID: 0d8f598d88ce
Revises: b191fbbd9630
Create Date: 2022-12-05 11:29:57.467029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8f598d88ce'
down_revision = 'b191fbbd9630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
