"""updated

Revision ID: 16c10c0f26b4
Revises: 6d5e6afcd5c9
Create Date: 2022-10-18 14:01:54.399169

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '16c10c0f26b4'
down_revision = '6d5e6afcd5c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
