"""create inital tables

Revision ID: 2e8110dab681
Revises: 3be67b736491
Create Date: 2022-10-15 16:06:44.139325

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e8110dab681'
down_revision = '3be67b736491'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('description', sa.Text(), nullable=True), schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'description', schema='content')
    # ### end Alembic commands ###
