"""create inital tables

Revision ID: 2e8b02682c10
Revises: 9eed3984bd88
Create Date: 2022-09-24 21:46:25.200425

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e8b02682c10'
down_revision = '9eed3984bd88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
