"""create inital tables

Revision ID: 3be67b736491
Revises: 75bac7ccd1ea
Create Date: 2022-09-24 21:46:28.809579

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3be67b736491'
down_revision = '75bac7ccd1ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
