"""updated

Revision ID: 3dde5ed298a1
Revises: 9e99342799fd
Create Date: 2022-10-26 18:06:57.322265

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3dde5ed298a1'
down_revision = '9e99342799fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE statusapplicationenum ADD VALUE 'read'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
