"""create inital tables

Revision ID: 42917e680c69
Revises: 4d1b2db101f2
Create Date: 2022-09-24 21:17:50.561357

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42917e680c69'
down_revision = '4d1b2db101f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'ride', schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('ride', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='content')
    # ### end Alembic commands ###
