"""updated

Revision ID: 4330c4371b36
Revises: 7cdf0b10e532
Create Date: 2022-11-27 19:13:02.171958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4330c4371b36'
down_revision = '7cdf0b10e532'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
