"""create inital tables

Revision ID: 4d1b2db101f2
Revises: 09a991741020
Create Date: 2022-09-24 21:17:00.750763

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d1b2db101f2'
down_revision = '09a991741020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('ride', sa.Boolean(), nullable=True), schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'ride', schema='content')
    # ### end Alembic commands ###
