"""updated

Revision ID: 6d5e6afcd5c9
Revises: 2e8110dab681
Create Date: 2022-10-18 14:00:10.984718

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '6d5e6afcd5c9'
down_revision = '2e8110dab681'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True), schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'email', schema='content')
    # ### end Alembic commands ###
