"""create inital tables

Revision ID: 75bac7ccd1ea
Revises: 2e8b02682c10
Create Date: 2022-09-24 21:46:27.616642

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '75bac7ccd1ea'
down_revision = '2e8b02682c10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
