"""updated

Revision ID: 7d3ed7667bc7
Revises: 0d8f598d88ce
Create Date: 2022-12-05 11:31:42.656574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3ed7667bc7'
down_revision = '0d8f598d88ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
