"""updated

Revision ID: 9e99342799fd
Revises: 16c10c0f26b4
Create Date: 2022-10-26 15:07:38.575865

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9e99342799fd'
down_revision = '16c10c0f26b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
