"""create inital tables

Revision ID: 9eed3984bd88
Revises: b165b637258c
Create Date: 2022-09-24 21:46:23.006509

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9eed3984bd88'
down_revision = 'b165b637258c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
