"""updated

Revision ID: b191fbbd9630
Revises: 4330c4371b36
Create Date: 2022-11-27 19:16:33.875347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b191fbbd9630'
down_revision = '4330c4371b36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE statusapplicationenum ADD VALUE 'mint'")
        op.execute("ALTER TYPE statusapplicationenum ADD VALUE 'new'")
        op.execute("ALTER TYPE statusapplicationenum ADD VALUE 'book'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
