"""updated

Revision ID: e5b08e7fa1d6
Revises: f3f6c2f6ab31
Create Date: 2022-12-30 11:01:48.222814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b08e7fa1d6'
down_revision = 'f3f6c2f6ab31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
