"""updated

Revision ID: f3f6c2f6ab31
Revises: 7d3ed7667bc7
Create Date: 2022-12-05 13:00:14.476791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f6c2f6ab31'
down_revision = '7d3ed7667bc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
