# Generated by Django 4.1.7 on 2023-11-30 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nft_tokens", "0008_alter_collection_symbol"),
    ]

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS billing;"),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сумма, в копейках"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email покупателя"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name=(
                            "Идентификатор платежа в системе Тинькофф Кассы"
                        ),
                    ),
                ),
                (
                    "payment_url",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ссылка на платежную форму",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="CREATED",
                        max_length=20,
                        verbose_name="Статус транзакции",
                    ),
                ),
                (
                    "tokens",
                    models.ManyToManyField(
                        to="nft_tokens.token",
                        verbose_name="приобретаемые сертификаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": 'billing"."order',
            },
        ),
    ]
