# Generated by Django 4.1.7 on 2024-03-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "nft_tokens",
            "0014_remove_pack_pack_uniq_name_and_collection_and_more",
        ),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Стоимость")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Withdrawal", "Вывод"),
                            ("Refund", "Возврат"),
                            ("Withdrawn", "Выведено"),
                            ("Returned", "Возвращено"),
                        ],
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                ("accrual", models.FloatField(verbose_name="Начислено")),
                (
                    "max_accrual",
                    models.FloatField(verbose_name="Максимально начислено"),
                ),
                ("withdrawal", models.FloatField(verbose_name="Выведено")),
                ("to_withdraw", models.FloatField(verbose_name="К выводу")),
                ("to_return", models.FloatField(verbose_name="К возврату")),
                (
                    "owner",
                    models.CharField(max_length=100, verbose_name="Владелец"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email владельца",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата"
                    ),
                ),
                (
                    "tokens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nft_tokens.token",
                        verbose_name="Токен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция токена",
                "verbose_name_plural": "Транзакции токенов",
                "db_table": "billing_token_transaction",
            },
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.CharField(max_length=255)),
                ("new_value", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.tokentransaction",
                    ),
                ),
            ],
        ),
    ]
