services:
  auth_base:
    restart: always
    networks:
      - dev_backend_network
      - dev_auth_network
    environment:
      - JWT_SECRET_KEY=${DEV_AUTH_SERVICE_JWT_SECRET_KEY}
      - SECRET_KEY=${DEV_AUTH_SERVICE_SECRET_KEY}
      - DB_NAME=${DEV_AUTH_DB_NAME}
      - DB_USER=${DEV_AUTH_DB_USER}
      - DB_PASSWORD=${DEV_AUTH_DB_PASSWORD}
      - DB_PORT=${DEV_AUTH_DB_PORT}
      - DB_HOST=${DEV_AUTH_DB_HOST}
      - REDIS_HOST=${DEV_AUTH_REDIS_HOST}
      - REDIS_PORT=${DEV_AUTH_REDIS_PORT}
      - REDIS_PASSWORD=${DEV_AUTH_REDIS_PASSWORD}

      - AUTH_EMAIL_HOST=${DEV_AUTH_EMAIL_HOST}
      - AUTH_EMAIL_PORT=${DEV_AUTH_EMAIL_PORT}
      - AUTH_EMAIL_HOST_USER=${DEV_AUTH_EMAIL_HOST_USER}
      - AUTH_EMAIL_HOST_PASSWORD=${DEV_AUTH_EMAIL_HOST_PASSWORD}
      - AUTH_EMAIL_DEFAULT_FROM_EMAIL=${DEV_AUTH_EMAIL_DEFAULT_FROM_EMAIL}
