version: '3.9'

services:

  admin_service:
    image: mwtechdocker/checkbrand-admin-service:${DEV_IMAGES_TAG}
    extends:
      file: ../admin/service/dev_admin_base.yml
      service: admin_panel_base
    depends_on:
      - admin_db
      - admin_redis
    container_name: dev_admin_service_admin
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:${DEV_ADMIN_PORT}"]
    volumes:
      - admin_static_volume:/usr/admin_panel/src/staticfiles
    expose:
      - "${DEV_ADMIN_PORT}"
    environment:
      - SERVER_NAME=admin_panel

  admin_celery_worker:
    image: mwtechdocker/checkbrand-admin-service:${DEV_IMAGES_TAG}
    extends:
      file: ../admin/service/dev_admin_base.yml
      service: admin_panel_base
    depends_on:
      - admin_db
      - admin_redis
    container_name: dev_admin_service_celery_worker
    command: ["celery", "-A", "config", "worker", "-l", "info"]
    environment:
      - SERVER_NAME=celery_worker

  admin_db:
    container_name: dev_admin_service_db
    image: postgres:16.0-alpine
    networks:
      - dev_admin_network
    restart: always
    volumes:
      - admin_postgres_data:/var/lib/postgresql/data/
    command: ["-p", "${DEV_ADMIN_DB_PORT}"]
    ports:
      - "${DEV_ADMIN_DB_PORT}:${DEV_ADMIN_DB_PORT}"

    expose:
      - "${DEV_ADMIN_DB_PORT}"
    environment:
      - POSTGRES_USER=${DEV_ADMIN_DB_USER}
      - POSTGRES_PASSWORD=${DEV_ADMIN_DB_PASSWORD}
      - POSTGRES_DB=${DEV_ADMIN_DB_NAME}

  admin_redis:
    container_name: dev_admin_service_redis
    image: redis:7.2.2-alpine
    networks:
      - dev_admin_network
    restart: always
    expose:
      - "${DEV_ADMIN_REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DEV_ADMIN_REDIS_PASSWORD} --port ${DEV_ADMIN_REDIS_PORT}

networks:
  dev_backend_network:
    external: true
  dev_admin_network:
    name: dev_admin_service_network

volumes:
  admin_postgres_data:
    name: dev_admin_service_db_data_volume
  admin_static_volume:
    name: dev_admin_service_static_data_volume
