version: '3.9'

services:
  
  nginx:
    container_name: dev_nginx
    restart: always
    image: "nginx:1.25.2-alpine-slim"
    networks:
      - dev_backend_network
    volumes:
      - "dev_admin_service_static_data_volume:/usr/admin_panel/src/staticfiles:ro"
      - "dev_auth_service_media_data_volume:/usr/auth/src/media:ro"
      - "dev_cerbot_www_volume:/var/www/certbot/:ro"
      # - "dev_cerbot_conf_volume:/etc/nginx/ssl/:ro" Комментируем в локальном
      - "../../../nginx/ssl:/etc/nginx/ssl:ro" # Используем только локально
      - "../../../nginx/nginx.conf:/etc/nginx/nginx.conf:ro" 
      - "../../../nginx/templates:/etc/nginx/templates:ro"
      - "../../../nginx/cors.conf:/etc/nginx/conf.d/config/cors.conf"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth_rest
      - admin_service
    environment:
      DOMEN: ${DEV_DOMAIN}
      AUTH_HOST: ${DEV_AUTH_REST_HOST}
      AUTH_PORT: ${DEV_AUTH_REST_PORT}
      ADMIN_HOST: ${DEV_ADMIN_HOST}
      ADMIN_PORT: ${DEV_ADMIN_PORT}
      HANDLER_HOST: ${DEV_HANDLER_API_SERVICE_HOST}
      HANDLER_PORT: ${DEV_HANDLER_API_SERVICE_PORT}

  certbot:
    image: certbot/certbot:latest
    volumes:
      - dev_cerbot_www_volume:/var/www/certbot/:rw
      - dev_cerbot_conf_volume:/etc/letsencrypt/:rw

networks:
  dev_backend_network:
    external: true

volumes:
  dev_cerbot_www_volume:
  dev_cerbot_conf_volume:
  dev_admin_service_static_data_volume:
    external: true
  dev_auth_service_media_data_volume:
    external: true
