version: '3.9'

services:
  
  nginx:
    container_name: local_nginx
    restart: always
    image: "nginx:1.25.2-alpine-slim"
    networks:
      - local_backend_network
    volumes:
      - "local_admin_service_static_data_volume:/usr/admin_panel/src/staticfiles:ro"
      - "local_auth_service_media_data_volume:/usr/auth/src/media:ro"
      - "local_cerbot_www_volume:/var/www/certbot/:ro"
      # - "local_cerbot_conf_volume:/etc/nginx/ssl/:ro" Комментируем в локальном
      - "../../../nginx/ssl:/etc/nginx/ssl:ro" # Используем только локально
      - "../../../nginx/nginx.conf:/etc/nginx/nginx.conf:ro" 
      - "../../../nginx/templates:/etc/nginx/templates:ro"
      - "../../../nginx/cors.conf:/etc/nginx/conf.d/config/cors.conf"

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth_rest
      - admin_service
    environment:
      DOMEN: ${LOCAL_DOMAIN}
      AUTH_HOST: ${LOCAL_AUTH_REST_HOST}
      AUTH_PORT: ${LOCAL_AUTH_REST_PORT}
      ADMIN_HOST: ${LOCAL_ADMIN_HOST}
      ADMIN_PORT: ${LOCAL_ADMIN_PORT}
      HANDLER_HOST: ${LOCAL_HANDLER_API_SERVICE_HOST}
      HANDLER_PORT: ${LOCAL_HANDLER_API_SERVICE_PORT}
  certbot:
    image: certbot/certbot:latest
    volumes:
      - local_cerbot_www_volume:/var/www/certbot/:rw
      - local_cerbot_conf_volume:/etc/letsencrypt/:rw

networks:
  local_backend_network:
    external: true

volumes:
  local_cerbot_www_volume:
  local_cerbot_conf_volume:
  local_admin_service_static_data_volume:
    external: true
  local_auth_service_media_data_volume:
    external: true
