# Generated by Django 4.1 on 2023-02-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS content;"),
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=255)),
                ("token_name", models.CharField(max_length=255)),
                ("full_url", models.URLField()),
                ("url_hash", models.SlugField(unique=True)),
                ("clicks", models.IntegerField(default=0)),
                ("generate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Short url",
                "verbose_name_plural": "Short urls",
                "db_table": 'content"."short_url',
            },
        ),
    ]
