[tool.black]
target-version = ['py310']
exclude = '/migrations/'
line_length = 79
preview = 1

[tool.isort]
line_length = 79
skip = ['migrations']
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.ruff]
target-version = "py310"
exclude = [
    "migrations",
]
line-length = 99

[tool.ruff.per-file-ignores]
"./config/settings/dev.py" = ["F403", "F401"]
"./nft_tokens/apps.py" = ["F401"]
