# Generated by Django 4.1.5 on 2023-01-14 14:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('content_type', models.CharField(choices=[('test', 'Test'), ('added_to_white_list', 'Add White List')], default='test', max_length=64, verbose_name='content type')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'db_table': 'content"."template',
            },
        ),
    ]
