# Generated by Django 4.1.5 on 2023-01-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemail',
            name='body',
        ),
        migrations.RemoveField(
            model_name='templatemail',
            name='title',
        ),
        migrations.AddField(
            model_name='templatemail',
            name='body_html',
            field=models.TextField(default=1, verbose_name='body_html'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatemail',
            name='body_text',
            field=models.TextField(default=1, verbose_name='body_text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatemail',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatemail',
            name='content_type',
            field=models.CharField(choices=[('test', 'Test'), ('added_white_list', 'Add White List'), ('booking_started', 'Booking Started'), ('added_white_list_and_booking', 'Add White List And Book'), ('user_booked', 'User Book'), ('minting_1_started', 'Mint 1 Start'), ('added_white_and_expects', 'Add White List And Expects'), ('minting_2_started', 'Mint 2 Start'), ('added_white_list_and_minting_2', 'Add White List And Mint 2'), ('user_minted', 'User Mint'), ('minting_stopped', 'Mint Stop')], default='test', max_length=64, unique=True, verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='templatemail',
            name='payload',
            field=models.JSONField(verbose_name='example_payload'),
        ),
    ]
